# Generated by Django 3.0.9 on 2020-08-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('watering_frequency', models.CharField(choices=[('REG', 'regularly'), ('INF', 'infrequently')], max_length=3)),
                ('watering_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
