# Generated by Django 3.0.9 on 2020-08-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20200804_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='text',
            field=models.TextField(default='...'),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
