# Generated by Django 3.0.9 on 2020-08-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_plant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='images/icon.png', upload_to='images/'),
        ),
    ]
