# Generated by Django 3.0.9 on 2020-08-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_auto_20200818_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='images/icon.png', upload_to='images/'),
        ),
    ]
