# Generated by Django 3.0.9 on 2020-08-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_auto_20200818_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
