# Generated by Django 3.0.9 on 2020-08-18 19:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants', '0009_auto_20200818_2025'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plant',
            unique_together={('name', 'owner')},
        ),
    ]
