# Generated by Django 3.0.9 on 2020-08-18 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_auto_20200818_2115'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plant',
            unique_together=set(),
        ),
    ]
