# Generated by Django 3.0.9 on 2020-08-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0012_auto_20200820_1753'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plant',
            unique_together=set(),
        ),
    ]
