# Generated by Django 3.0.9 on 2020-08-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0013_auto_20200820_1900'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_name'),
        ),
    ]
