# Generated by Django 3.0.9 on 2020-08-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0014_auto_20200820_2040'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plant',
            name='unique_name',
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.UniqueConstraint(fields=('name', 'owner_id'), name='unique_name'),
        ),
    ]
